pool:  
  name: Default 
#   vmImage: ubuntu-latest

trigger: none
# - main

variables:
  acr_name: contosoteam7
  tag: 1.0.0-$(Build.BuildId)

steps:

- task: AzureCLI@2
  displayName: Docker Build & Push
  inputs:
    azureSubscription: 'aksha'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t acrjv1971.azurecr.io/webapp:$(tag) app-dotnet
      az acr login -n acrjv1971
      docker push acrjv1971.azurecr.io/webapp:$(tag)
      
- task: replacetokens@4
  displayName: 'Replace Image TAG'
  inputs:
    rootDirectory: '02_kubernetes_aks'
    targetFiles: 'app-deploy.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '__'
    tokenSuffix: '__'
    useLegacyPattern: false
    enableTransforms: false
    enableTelemetry: true

- script: type 02_kubernetes_aks\app-deploy.yaml

- task: Kubernetes@1
  displayName: Kubernetes Deploy
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'aksha'
    azureResourceGroup: 'aksha'
    kubernetesCluster: 'aksha'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '02_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
